version: "3"
services:
  web: 
    container_name: ${PROJECT_NAME}_web
    build: ./docker/php
    volumes:
      - .:${PROJECT_PATH}
      - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/apache/var/log/apache2:/var/log/apache2
      - ./docker/php/etc/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    ports:
      - "8082:80"
    
  db:
    container_name: ${PROJECT_NAME}_mysql
    build: ./docker/mysql
    volumes:
      - ./docker/db/db_data:/var/lib/mysql
    environment:
      -  MYSQL_USER=${DB_USER_NAME}
      -  MYSQL_PASSWORD=${DB_USER_PASSWORD}
      -  MYSQL_DATABASE=${DB_NAME}
      -  MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 3306
  
  app:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:
      - PMA_ARBITRARY=1
     restart: always
     links:
      - db
     ports:
      - 8080:80
     volumes:
      - /sessions
     
volumes:
  db_data: